[project]
name = "expert-fishstick"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
]

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "pytest>=8.4.2",
    "ruff>=0.13.2",
]
[build-system]
requires = ["uv_build>=0.8.6,<0.9.0"]
build-backend = "uv_build"